export {
  reduceEffectiveBoard,
  type EffectiveBoardBounds,
  type EffectiveBoardReduction,
  type EffectiveBoardReductionOptions,
  type EffectiveCell,
  type EffectiveCellReason,
} from './antiClone.js'
export {
  evaluateAntiCloneReport,
  type AntiCloneEvidenceGroup,
  type AntiCloneEvidenceKind,
  type AntiCloneReport,
  type AntiCloneReportOptions,
  type AntiCloneReportStatus,
} from './antiCloneReport.js'
export { antiCloneCommand, type AntiCloneCommandOptions } from './antiCloneCommand.js'
export {
  AUTHORING_CLI_VERSION,
  AUTHORING_PACKAGE_NAME,
  type AntiCloneCommand,
  type AuthoringCaseValidationReport,
  type AuthoringCliCommand,
  type AuthoringCliDiagnostic,
  type AuthoringCliOptions,
  type AuthoringCliParseError,
  type AuthoringCliParseResult,
  type AuthoringCliReport,
  type AuthoringCommandName,
  type AuthoringDifficultyReviewBucket,
  type AuthoringDifficultyReviewReport,
  type AuthoringDifficultyThresholdReport,
  type AuthoringOutputFormat,
  type AuthoringRecommendation,
  type AuthoringSchemaIssueReport,
  type AuthoringSolverCapsReport,
  type AuthoringSolverStatsReport,
  type AuthoringTechniqueRetentionReport,
  type CasePathCommand,
  type SampleCommand,
} from './contracts.js'
export { minimizeCaseCommand, scoreCaseCommand } from './caseCommands.js'
export {
  DEFAULT_CAPS,
  emptyValidation,
  evaluateDraftDiagnostics,
  solverCaps,
  validatePuzzleInput,
  type AuthoringCopyWarning,
  type AuthoringDiagnosticsGroup,
  type AuthoringDiagnosticsGroupId,
  type AuthoringDiagnosticsItem,
  type AuthoringDiagnosticsSeverity,
  type AuthoringDraftDiagnosticsInput,
  type AuthoringDraftDiagnosticsReport,
  type AuthoringDraftDiagnosticsStatus,
  type AuthoringDraftQualityReport,
} from './diagnostics.js'
export {
  createEmptyWorkbenchDraftState,
  exportDraftJson,
  formatDraftJson,
  importJsonTextToDraftState,
  importPuzzleToDraftState,
  normalizedDraftTargetCell,
  patchDraftAllowedKinds,
  patchDraftAnchors,
  patchDraftBoardSize,
  patchDraftMetadata,
  patchDraftNormalizedTargetCell,
  patchDraftRecords,
  patchDraftRegions,
  patchDraftRulePresentation,
  patchDraftRules,
  patchDraftTargetCell,
  patchDraftTargetCells,
  parseDraftJson,
  selectDraftCell,
  selectDraftRule,
  toggleDraftInitialReveal,
  updateDraftJsonText,
  type WorkbenchDraftExportResult,
  type WorkbenchDraftImportOptions,
  type PatchDraftMetadataInput,
  type PatchDraftRulePresentationInput,
  type WorkbenchDraftPatchResult,
  type WorkbenchDraftParseResult,
  type WorkbenchDraftSource,
  type WorkbenchDraftSourceKind,
  type WorkbenchDraftState,
} from './drafts.js'
export {
  createRuleBuilderDraft,
  createRuleBuilderDrafts,
  duplicateRuleBuilderDraft,
  editableRuleTypes,
  exportRuleBuilderDrafts,
  moveRuleBuilderDraft,
  type RuleBuilderDraft,
  type RuleBuilderSupport,
} from './ruleBuilder.js'
export {
  forbiddenRuleTextTerms,
  generateRuleText,
  type GeneratedRuleText,
  type RuleTextContext,
  type RuleTextLocale,
} from './ruleText.js'
export {
  compileRuleExpression,
  generateRuleExpressionText,
  type RuleExpression,
  type RuleExpressionCompileBlockCode,
  type RuleExpressionCompileContext,
  type RuleExpressionCompileResult,
  type RuleExpressionGeneratedText,
  type RuleExpressionLocalRelation,
  type RuleExpressionPredicate,
  type RuleExpressionScope,
  type RuleExpressionSelector,
  type RuleExpressionSyntheticRegion,
} from './ruleExpression.js'
export {
  createEmptyThemePackageDraft,
  evaluateThemePackageDraft,
  REQUIRED_THEME_ASSET_KINDS,
  type DialogueHookKind,
  type ThemeAssetIntakeItem,
  type ThemeAssetKind,
  type ThemeAssetStatus,
  type ThemeDialogueHook,
  type ThemeDialogueLine,
  type ThemePackageDraft,
  type ThemePackageEvaluation,
  type ThemePackageIssue,
  type ThemePackageIssueCode,
} from './themePackage.js'
export {
  evaluateNoveltyClaimManifest,
  type NoveltyClaim,
  type NoveltyClaimEvidence,
  type NoveltyClaimIssue,
  type NoveltyClaimIssueCode,
  type NoveltyClaimManifest,
  type NoveltyClaimReport,
  type NoveltyClaimStatus,
} from './noveltyClaims.js'
export {
  evaluateReviewerManifest,
  type ReviewerManifest,
  type ReviewerManifestBucket,
  type ReviewerManifestCase,
  type ReviewerManifestDecision,
  type ReviewerManifestGateEvidence,
  type ReviewerManifestGateStatus,
  type ReviewerManifestIssue,
  type ReviewerManifestIssueCode,
  type ReviewerManifestReport,
} from './reviewerManifest.js'
export {
  evaluateSkeletonReview,
  type SkeletonReviewClaims,
  type SkeletonReviewGate,
  type SkeletonReviewGateId,
  type SkeletonReviewInput,
  type SkeletonReviewMetrics,
  type SkeletonReviewReport,
  type SkeletonReviewStatus,
} from './skeletonReview.js'
export { commandInputPath, parseAuthoringArgs } from './parser.js'
export {
  candidateShrinkSignature,
  canonicalEffectivePuzzleIsomorphismSignature,
  canonicalPuzzleIsomorphismSignature,
  evaluateCoreQualityGates,
  evaluateDegeneracyGates,
  evaluateRuleFamilyDiversityGate,
  evaluateRuleContribution,
  evaluateRuleImpactVector,
  evaluateTechniqueRetentionGate,
  findCandidateShrinkCloneGroups,
  findEffectiveIsomorphicPuzzleGroups,
  findIsomorphicPuzzleGroups,
  findProofTraceCloneGroups,
  findRuleImpactCloneGroups,
  proofTraceFingerprint,
  ruleImpactVectorSignature,
  type BoardTransformName,
  type CandidateShrinkCheckpoint,
  type CandidateShrinkCloneGroup,
  type CandidateShrinkSignature,
  type DegeneracyGateOptions,
  type DegeneracyGateReport,
  type DegeneracyGateResult,
  type DegeneracyGateStatus,
  type DegeneracyReason,
  type DegeneracyScopeKind,
  type EffectivePuzzleIsomorphismGroup,
  type EffectivePuzzleIsomorphismSignature,
  type MaterialRuleFamily,
  type ProofTraceCloneGroup,
  type ProofTraceCloneMatchKind,
  type ProofTraceCloneStatus,
  type ProofTraceFingerprint,
  type ProofTraceStepFingerprint,
  type ProofTraceTransformSignature,
  type PuzzleIsomorphismGroup,
  type PuzzleIsomorphismSignature,
  type PuzzleTransformSignature,
  type QualityGateCaseProfile,
  type QualityGateId,
  type QualityGateInput,
  type QualityGatePolicy,
  type QualityGateReport,
  type QualityGateResult,
  type QualityGateStatus,
  type RuleContributionOptions,
  type RuleContributionReason,
  type RuleContributionReport,
  type RuleContributionResult,
  type RuleContributionStatus,
  type RuleFamilyDiversityEntry,
  type RuleFamilyDiversityOptions,
  type RuleFamilyDiversityReason,
  type RuleFamilyDiversityReport,
  type RuleImpactCloneGroup,
  type RuleImpactVectorEntry,
  type RuleImpactVectorReport,
  type RuleImpactVectorSignature,
  type RuleImpactVectorStatus,
  type TechniqueRetentionGateInput,
  type TechniqueRetentionGateReport,
} from './qualityGates.js'
export { parsedCommandReport, parseErrorReport } from './reports.js'
export { runAuthoringCli, type RunAuthoringCliOptions } from './runner.js'
export { sampleCommand } from './sampleCommand.js'
export { validateCaseCommand } from './validation.js'
