export {
  reduceEffectiveBoard,
  type EffectiveBoardBounds,
  type EffectiveBoardReduction,
  type EffectiveBoardReductionOptions,
  type EffectiveCell,
  type EffectiveCellReason,
} from './antiClone.js'
export {
  evaluateAntiCloneReport,
  type AntiCloneEvidenceGroup,
  type AntiCloneEvidenceKind,
  type AntiCloneReport,
  type AntiCloneReportOptions,
  type AntiCloneReportStatus,
} from './antiCloneReport.js'
export { antiCloneCommand, type AntiCloneCommandOptions } from './antiCloneCommand.js'
export {
  AUTHORING_CLI_VERSION,
  AUTHORING_PACKAGE_NAME,
  type AntiCloneCommand,
  type AuthoringCaseValidationReport,
  type AuthoringCliCommand,
  type AuthoringCliDiagnostic,
  type AuthoringCliOptions,
  type AuthoringCliParseError,
  type AuthoringCliParseResult,
  type AuthoringCliReport,
  type AuthoringCommandName,
  type AuthoringOutputFormat,
  type AuthoringRecommendation,
  type AuthoringSchemaIssueReport,
  type AuthoringSolverCapsReport,
  type AuthoringSolverStatsReport,
  type AuthoringTechniqueRetentionReport,
  type CasePathCommand,
  type SampleCommand,
} from './contracts.js'
export { minimizeCaseCommand, scoreCaseCommand } from './caseCommands.js'
export {
  evaluateNoveltyClaimManifest,
  type NoveltyClaim,
  type NoveltyClaimEvidence,
  type NoveltyClaimIssue,
  type NoveltyClaimIssueCode,
  type NoveltyClaimManifest,
  type NoveltyClaimReport,
  type NoveltyClaimStatus,
} from './noveltyClaims.js'
export { commandInputPath, parseAuthoringArgs } from './parser.js'
export {
  candidateShrinkSignature,
  canonicalEffectivePuzzleIsomorphismSignature,
  canonicalPuzzleIsomorphismSignature,
  evaluateCoreQualityGates,
  evaluateDegeneracyGates,
  evaluateRuleFamilyDiversityGate,
  evaluateRuleContribution,
  evaluateRuleImpactVector,
  evaluateTechniqueRetentionGate,
  findCandidateShrinkCloneGroups,
  findEffectiveIsomorphicPuzzleGroups,
  findIsomorphicPuzzleGroups,
  findProofTraceCloneGroups,
  findRuleImpactCloneGroups,
  proofTraceFingerprint,
  ruleImpactVectorSignature,
  type BoardTransformName,
  type CandidateShrinkCheckpoint,
  type CandidateShrinkCloneGroup,
  type CandidateShrinkSignature,
  type DegeneracyGateOptions,
  type DegeneracyGateReport,
  type DegeneracyGateResult,
  type DegeneracyGateStatus,
  type DegeneracyReason,
  type DegeneracyScopeKind,
  type EffectivePuzzleIsomorphismGroup,
  type EffectivePuzzleIsomorphismSignature,
  type MaterialRuleFamily,
  type ProofTraceCloneGroup,
  type ProofTraceCloneMatchKind,
  type ProofTraceCloneStatus,
  type ProofTraceFingerprint,
  type ProofTraceStepFingerprint,
  type ProofTraceTransformSignature,
  type PuzzleIsomorphismGroup,
  type PuzzleIsomorphismSignature,
  type PuzzleTransformSignature,
  type QualityGateCaseProfile,
  type QualityGateId,
  type QualityGateInput,
  type QualityGatePolicy,
  type QualityGateReport,
  type QualityGateResult,
  type QualityGateStatus,
  type RuleContributionOptions,
  type RuleContributionReason,
  type RuleContributionReport,
  type RuleContributionResult,
  type RuleContributionStatus,
  type RuleFamilyDiversityEntry,
  type RuleFamilyDiversityOptions,
  type RuleFamilyDiversityReason,
  type RuleFamilyDiversityReport,
  type RuleImpactCloneGroup,
  type RuleImpactVectorEntry,
  type RuleImpactVectorReport,
  type RuleImpactVectorSignature,
  type RuleImpactVectorStatus,
  type TechniqueRetentionGateInput,
  type TechniqueRetentionGateReport,
} from './qualityGates.js'
export { parsedCommandReport, parseErrorReport } from './reports.js'
export { runAuthoringCli, type RunAuthoringCliOptions } from './runner.js'
export { sampleCommand } from './sampleCommand.js'
export { validateCaseCommand } from './validation.js'
